//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseManage.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int Id { get; set; }
        public string Community { get; set; }
        public string Building { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<System.DateTime> TakeDate { get; set; }
        public Nullable<int> Expiration { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Owner { get; set; }
        public string Contact { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FirstLetter { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.DateTime> PayRentDate { get; set; }
        public Nullable<int> PayRentMonths { get; set; }
        public Nullable<decimal> PayMoney { get; set; }
        public string Card { get; set; }
        public string PayRentType { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string Remarks { get; set; }
        public string Point { get; set; }
        public string ShowName { get; set; }
    }
}
