//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseManage.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HouseManageEntities : DbContext
    {
        public HouseManageEntities()
            : base("name=HouseManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Expend> Expend { get; set; }
        public virtual DbSet<FirstLetter> FirstLetter { get; set; }
        public virtual DbSet<Revenue> Revenue { get; set; }
        public virtual DbSet<Tenant> Tenant { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<Suggestion> Suggestion { get; set; }
        public virtual DbSet<Point> Point { get; set; }
        public virtual DbSet<RoomLog> RoomLog { get; set; }
    }
}
