//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseManage.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int Id { get; set; }
        public Nullable<int> HouseId { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Rent { get; set; }
        public string Tenants { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<int> Expiration { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<System.DateTime> PayRentDate { get; set; }
        public Nullable<int> PayRentMonths { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string PayRentType { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string Url { get; set; }
    }
}
